name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline (skip ingestion)
        run: |
          python -m ingestion.clean_transform
          python -m db.db_schema
          python -m db.load_to_db
          python -m analytics.forecasting
          python -m analytics.reporting
          python -m analytics.visualization

      - name: Run tests
        run: |
          python -m pytest

      - name: Show Streamlit App URL
        if: success()
        run: |
          echo "Your dashboard is live at: https://greenpower.streamlit.app/"
          echo "::notice title=Streamlit Dashboard::Access your dashboard at https://greenpower.streamlit.app/"
