name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Show working directory
        run: |
          pwd
          ls -l

      - name: Run data pipeline
        run: |
          python -m run_pipeline

      - name: Run tests
        run: |
          python -m pytest

      - name: Show Streamlit App URL
        if: success()
        run: |
          echo "Your dashboard is live at: https://greenpower.streamlit.app/"
          echo "::notice title=Streamlit Dashboard::Access your dashboard at https://greenpower.streamlit.app/"
